Feature/translate en
stack-spot/mind-dotnet-worker-stack pull request #7
Opened 2022-10-18 19:06 UTC by ricardojosezup

2022-10-19 16:36 UTC, pilzzup requested changes

2022-10-19 16:36 UTC, pilzzup commented on docs/about_en-us.md
> +Develop and publish Background Services to connect company software to your product with **Stack Cloud Native .NET**. The Stack includes support for Clean Arch, observability, connecting to queues, a
Replicar readme

2022-10-20 15:00 UTC, jessica-tw commented on docs/use-case_en-us.md
> +Check below the capabilities available to be added to a base Template.
```suggestion
Check the capabilities available that you can add to a base Template.
```

2022-10-20 15:00 UTC, jessica-tw commented on stack.yaml
> +description: Develop and publish Workers that run company routines in your product with our Stack cloud native .NET.
```suggestion
description: Develop and publish Workers that run company routines in your product with our cloud-native .NET Stack.
```

2022-10-20 15:02 UTC, jessica-tw commented on docs/use-case_en-us.md
> +It's allow you to define Tags so that you can quantify and/or classify errors, providing a view of recurring failures or preventing future problems.
```suggestion
If you have several projects, microservices, and/or routines, with this Plugin you can maintain the quality and standard of the log information for everything, considering different log levels.

It allows you to define Tags, and you can quantify and/or classify errors, providing a view of recurring failures or preventing future problems.
```

2022-10-20 15:02 UTC, jessica-tw commented on docs/use-case_en-us.md
> +In addition, it is easy to integrate with tools such as **Splunk** or **AWS Cloud Watch** to monitor and visualize data, ensuring the observability of your applications.
```suggestion
It is also easy to integrate with tools such as **Splunk** or **AWS Cloud Watch** to monitor and visualize data, ensuring the observability of your applications.
```

2022-10-20 15:03 UTC, jessica-tw commented on docs/use-case_en-us.md
> +Trace Plugin facilitates telemetry instrumentation of your API, through **Opentelemetry**, with exporter for **Jaeger** and **AWS X-Ray**.
```suggestion
Trace Plugin facilitates telemetry instrumentation of your API, through **Opentelemetry**, with an exporter for **Jaeger** and **AWS X-Ray**.
```

2022-10-20 15:10 UTC, jessica-tw commented on docs/use-case_en-us.md
> +The Queue Plugin simplifies the entire configuration and implementation of a decentralized environment, focused on microservices that communicate with each other, using message queues. Compared to cr
```suggestion
The Queue Plugin simplifies the entire configuration and implementation of a decentralized environment, focused on microservices that communicate with each other, using message queues. It's like creating a class, the Plugin Queue manages to abstract all the complexity communicating with your **AWS SQS** queue.
```

2022-10-20 15:11 UTC, jessica-tw commented on docs/use-case_en-us.md
> +The Notification Plugin provides the features of **AWS SNS (Simple Notification Service)** so that your application can send messages to topics that will be consumed by your Subscribers, simultaneous
```suggestion
The Notification Plugin provides the **AWS SNS (Simple Notification Service)** features so your application can send messages to topics that will be consumed by your Subscribers, simultaneously sending data, information, and messages to different platforms at once.
```

2022-10-20 15:12 UTC, jessica-tw commented on docs/use-case_en-us.md
> +Use the Secrets plugin any time you want within your application.
```suggestion
Plugin Secrets makes the management of sensitive system information with API keys, authentication tokens, or database connections easier. It was thought of using a **Secret Manager** from AWS to simplify the consumption of this information.
Use the Secrets plugin any time you want in your application.
```

2022-10-20 15:13 UTC, jessica-tw commented on docs/use-case_en-us.md
> +Handle files using Plugin Bucket, it eliminates complexity and facilitates instrumentation with **Amazon Simple Storage Service (S3)**.
```suggestion
You can handle files using the Bucket Plugin. It eliminates the complexity and facilitates instrumentation with **Amazon Simple Storage Service (S3)**.
```

2022-10-20 15:13 UTC, jessica-tw commented on docs/use-case_en-us.md
> +Store data or documents trivially. Plugin Repository brings together all the capabilities of **AWS DynamoDB** in a simple and fast way.
```suggestion
Store data or documents trivially. Repository Plugin brings together all the capabilities of **AWS DynamoDB** in a simple and fast way.
```

2022-10-20 15:14 UTC, jessica-tw commented on docs/use-case_en-us.md
> +Plugin Authentication provides more security for you to easily verify a user/API accesses to the restricted resources of your API.
```suggestion
Authentication Plugin provides more security for you to easily verify a user/API access to the restricted resources of your API.
```

2022-10-20 15:15 UTC, jessica-tw commented on docs/use-case_en-us.md
> +The gRPC Plugin adds the ability to expose `gRPC` services and their settings, and provide the creation of a `gRPC Client`, that allows the distribution and consumption of this service in other appli
```suggestion
The gRPC Plugin adds the ability to expose `gRPC` services and their settings. It provides the creation of a `gRPC Client`, that allows the distribution and consumption of this service in other applications.
```

2022-10-20 15:15 UTC, jessica-tw commented on docs/use-case_en-us.md
> +**Check out more details such as ways to use and use cases of each Plugin in the left side menu.**
```suggestion
**See more details like ways to use and use cases of each Plugin on the left side menu.**
```

2022-10-20 20:10 UTC, jessica-tw approved these changes

2022-10-24 22:37 UTC, pilzzup approved these changes

2022-10-25 15:05 UTC, merged